import type { MapBiome, MapMood, TerrainKind } from "./map-package";

export type MapPromptCase = {
  id: string;
  prompt: string;
  seed: string;
  expectedBiome: MapBiome;
  expectedMood: MapMood;
  requiredFeature: string;
  requiredStamp?: string;
  distinctiveTerrain?: TerrainKind;
};

export const ORIGINAL_MAP_PROMPT_CASES: MapPromptCase[] = [
  {
    id: "haunted-moon-ruins",
    prompt: "Haunted ruins in moonlight. A broken shrine overlooks one open courtyard, with scattered bones and crumbling walls.",
    seed: "MOON-WRAITH-17",
    expectedBiome: "ruins",
    expectedMood: "moonlight",
    requiredFeature: "bones",
  },
  {
    id: "bone-cave-lair",
    prompt: "Cave lair scattered with bones. A narrow winding entrance widens into a large chamber with a shallow pool.",
    seed: "HOLLOW-FANG-23",
    expectedBiome: "cave",
    expectedMood: "daylight",
    requiredFeature: "bones",
  },
  {
    id: "forest-stream-crossing",
    prompt: "Ancient forest clearing split by a winding stream, with a fallen log crossing, a ritual stone ring, and dense trees around the edge.",
    seed: "GREEN-CROWN-31",
    expectedBiome: "forest",
    expectedMood: "daylight",
    requiredFeature: "stream",
  },
  {
    id: "torchlit-crypt",
    prompt: "Torchlit dungeon crypt with several compact rooms, a central tomb, scattered bones, and a direct corridor to a sealed door.",
    seed: "ASHEN-CRYPT-09",
    expectedBiome: "dungeon",
    expectedMood: "torchlight",
    requiredFeature: "bones",
  },
  {
    id: "flooded-cavern",
    prompt: "A vast flooded cavern with a twisting trail, stalagmite clusters, a rope bridge crossing dark water, and an open chamber beyond.",
    seed: "DEEP-TIDE-44",
    expectedBiome: "cave",
    expectedMood: "daylight",
    requiredFeature: "pond",
  },
  {
    id: "misty-roadside-ruins",
    prompt: "Overcast roadside ruins in drifting mist: a sparse broken watch post, rubble patches, an abandoned campfire, and a wide open approach.",
    seed: "GRAY-ROAD-12",
    expectedBiome: "ruins",
    expectedMood: "overcast",
    requiredFeature: "camp",
  },
];

export const ADDITIONAL_MAP_PROMPT_CASES: MapPromptCase[] = [
  {
    id: "moonlit-witch-bog",
    prompt: "Moonlit witch's bog in a deep swamp. Black pools surround a crooked ritual altar, glowing mushrooms, and twisted mangrove roots.",
    seed: "HEXFEN-41",
    expectedBiome: "swamp",
    expectedMood: "moonlight",
    requiredFeature: "mangroves",
    requiredStamp: "twisted-mangroves",
    distinctiveTerrain: "mud",
  },
  {
    id: "drowned-marsh-causeway",
    prompt: "Overcast drowned marsh causeway. A narrow earth road crosses a winding stream between reed beds and a broken rope bridge.",
    seed: "DROWNED-ROAD-08",
    expectedBiome: "swamp",
    expectedMood: "overcast",
    requiredFeature: "reeds",
    requiredStamp: "reed-bed",
    distinctiveTerrain: "mud",
  },
  {
    id: "lizardfolk-reed-camp",
    prompt: "Daylit lizardfolk wetland camp in a broad swamp. Shallow pools, dense reeds, a central campfire, and stacked supplies leave several muddy approaches.",
    seed: "SCALE-MARSH-26",
    expectedBiome: "swamp",
    expectedMood: "daylight",
    requiredFeature: "camp",
    requiredStamp: "campfire",
    distinctiveTerrain: "mud",
  },
  {
    id: "oasis-caravan-ambush",
    prompt: "Desert oasis caravan ambush. Wind-carved dunes surround a clear pool, an abandoned cart, scattered barrels, and one open trade road.",
    seed: "AMBER-OASIS-52",
    expectedBiome: "desert",
    expectedMood: "daylight",
    requiredFeature: "dunes",
    requiredStamp: "wind-carved-dunes",
    distinctiveTerrain: "sand",
  },
  {
    id: "red-canyon-shrine",
    prompt: "Overcast red desert canyon shrine. Boulder walls funnel travelers toward a ritual altar, a warding glyph, and a concealed spike pit.",
    seed: "RED-GORGE-13",
    expectedBiome: "desert",
    expectedMood: "overcast",
    requiredFeature: "pit trap",
    requiredStamp: "spike-pit",
    distinctiveTerrain: "sand",
  },
  {
    id: "buried-desert-necropolis",
    prompt: "Torchlit desert necropolis half buried by dunes. Broken crypt walls, bone fields, a stone altar, and sealed supplies frame a sunken court.",
    seed: "SAND-TOMB-63",
    expectedBiome: "desert",
    expectedMood: "torchlight",
    requiredFeature: "bones",
    requiredStamp: "bone-scatter",
    distinctiveTerrain: "sand",
  },
  {
    id: "salt-flat-battlefield",
    prompt: "Overcast salt flat battlefield. Old battle lines contain a shattered cart, scattered skeletons, low rubble, and a vast open center.",
    seed: "WHITE-WASTE-19",
    expectedBiome: "desert",
    expectedMood: "overcast",
    requiredFeature: "battlefield",
    requiredStamp: "abandoned-cart",
    distinctiveTerrain: "sand",
  },
  {
    id: "frozen-watchtower",
    prompt: "Overcast frozen watchtower on an exposed tundra ridge. Ice spires, a collapsed tower wall, and a narrow snow path overlook the approach.",
    seed: "FROST-WATCH-34",
    expectedBiome: "tundra",
    expectedMood: "overcast",
    requiredFeature: "ruined tower",
    requiredStamp: "ruined-l-wall",
    distinctiveTerrain: "snow",
  },
  {
    id: "aurora-stone-circle",
    prompt: "Moonlit aurora tundra stone circle. Standing stones and a glowing warding rune rise between ice spires on a wide sacred field.",
    seed: "AURORA-RING-77",
    expectedBiome: "tundra",
    expectedMood: "moonlight",
    requiredFeature: "ice spires",
    requiredStamp: "ice-spires",
    distinctiveTerrain: "snow",
  },
  {
    id: "glacial-crevasse-camp",
    prompt: "Daylit glacial crevasse expedition camp. A rope bridge spans a spike-filled chasm between ice spires, supplies, and a sheltered campfire.",
    seed: "BLUE-CLEFT-45",
    expectedBiome: "tundra",
    expectedMood: "daylight",
    requiredFeature: "pit trap",
    requiredStamp: "spike-pit",
    distinctiveTerrain: "snow",
  },
  {
    id: "snowbound-caravan",
    prompt: "Overcast snowbound caravan roadblock across the tundra. An abandoned cart, supply crates, boulder cover, and a winding trail divide the field.",
    seed: "WINTER-ROAD-58",
    expectedBiome: "tundra",
    expectedMood: "overcast",
    requiredFeature: "cart",
    requiredStamp: "abandoned-cart",
    distinctiveTerrain: "snow",
  },
  {
    id: "caldera-cult-ritual",
    prompt: "Moonlit volcanic caldera cult ritual. Lava vents surround standing stones, a warding rune, and a black altar on a narrow stone island.",
    seed: "CINDER-RITE-66",
    expectedBiome: "volcanic",
    expectedMood: "moonlight",
    requiredFeature: "lava vents",
    requiredStamp: "lava-vent",
    distinctiveTerrain: "lava",
  },
  {
    id: "obsidian-forge",
    prompt: "Torchlit obsidian forge in a volcanic waste. Lava vents, a stone altar, stacked supplies, and ruined walls form a compact industrial yard.",
    seed: "BLACK-FORGE-28",
    expectedBiome: "volcanic",
    expectedMood: "torchlight",
    requiredFeature: "supplies",
    requiredStamp: "crates-and-barrels",
    distinctiveTerrain: "ash",
  },
  {
    id: "ash-choked-battlefield",
    prompt: "Overcast ash-choked battlefield below a volcano. Bone scatters, a wrecked cart, rubble berms, and drifting ash cover a dense old battle line.",
    seed: "GRAY-LEGION-71",
    expectedBiome: "volcanic",
    expectedMood: "overcast",
    requiredFeature: "battlefield",
    requiredStamp: "bone-scatter",
    distinctiveTerrain: "ash",
  },
  {
    id: "fire-giant-approach",
    prompt: "Volcanic fire giant approach across a lava river. A rope bridge joins stone islands between boulder outcrops, supply caches, and molten vents.",
    seed: "GIANT-STEP-84",
    expectedBiome: "volcanic",
    expectedMood: "torchlight",
    requiredFeature: "bridge",
    requiredStamp: "rope-bridge",
    distinctiveTerrain: "lava",
  },
  {
    id: "pirate-smuggler-cove",
    prompt: "Moonlit pirate smuggler cove on a hidden coast. A broken vessel, campfire, supply crates, and narrow beach path surround dark tidal water.",
    seed: "SMUGGLER-MOON-37",
    expectedBiome: "coast",
    expectedMood: "moonlight",
    requiredFeature: "shipwreck",
    requiredStamp: "coastal-wreck",
    distinctiveTerrain: "water",
  },
  {
    id: "storm-lighthouse-ruins",
    prompt: "Overcast storm-lashed lighthouse ruins on a rocky coast. A collapsed tower, shipwreck timbers, boulder outcrops, and flooded steps face the sea.",
    seed: "STORM-BEACON-11",
    expectedBiome: "coast",
    expectedMood: "overcast",
    requiredFeature: "ruined tower",
    requiredStamp: "ruined-l-wall",
    distinctiveTerrain: "water",
  },
  {
    id: "sunken-tidal-temple",
    prompt: "Sunlit tidal temple on the coast. A ritual stone circle, broken fountain pool, warding glyph, and shallow water divide the exposed plaza.",
    seed: "TIDE-SHRINE-49",
    expectedBiome: "coast",
    expectedMood: "daylight",
    requiredFeature: "fountain",
    requiredStamp: "broken-fountain",
    distinctiveTerrain: "water",
  },
  {
    id: "shipwreck-salvage-beach",
    prompt: "Overcast shipwreck salvage beach. A beached vessel, abandoned cart, barrel cache, dunes, and an open shoreline create competing cover lanes.",
    seed: "SALVAGE-TIDE-22",
    expectedBiome: "coast",
    expectedMood: "overcast",
    requiredFeature: "shipwreck",
    requiredStamp: "coastal-wreck",
    distinctiveTerrain: "sand",
  },
  {
    id: "fey-thorn-labyrinth",
    prompt: "Moonlit fey forest thorn labyrinth. Dense bramble walls, glowing mushrooms, a warding rune, and an ancient stone circle surround one clearing.",
    seed: "FEY-HEDGE-93",
    expectedBiome: "forest",
    expectedMood: "moonlight",
    requiredFeature: "thicket",
    requiredStamp: "thorn-thicket",
    distinctiveTerrain: "grass",
  },
];

export const MAP_PROMPT_CASES: MapPromptCase[] = [...ORIGINAL_MAP_PROMPT_CASES, ...ADDITIONAL_MAP_PROMPT_CASES];
